// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDK8cqFAS03DSOBdeOh_IjUI8gSg-OvNA',
    appId: '1:593631179772:web:ef4d3b980dedc9511a7879',
    messagingSenderId: '593631179772',
    projectId: 'mobileappsassignone',
    authDomain: 'mobileappsassignone.firebaseapp.com',
    databaseURL: 'https://mobileappsassignone-default-rtdb.firebaseio.com',
    storageBucket: 'mobileappsassignone.appspot.com',
    measurementId: 'G-1877VKGL12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgcGkF-4reLWC2P0qb3lojpsovtfqE9qQ',
    appId: '1:593631179772:android:ab63c29a2b7fb2dd1a7879',
    messagingSenderId: '593631179772',
    projectId: 'mobileappsassignone',
    databaseURL: 'https://mobileappsassignone-default-rtdb.firebaseio.com',
    storageBucket: 'mobileappsassignone.appspot.com',
  );
}
